[workspace]
resolver = "2"
members = [
    "genesis-abi",
    "bitops",
    "kfmt",
    "sync",
    "arch-intrinsics",
    "alloc",
    "collections",
    "crypto",
    "elf",
    "devicetree",
]

[workspace.package]
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/terranox-os/kernel-libs"
