load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "kernel_sync",
    srcs = [
        "src/lib.rs",
        "src/spinlock.rs",
        "src/once.rs",
        "src/atomic_bitops.rs",
    ],
    crate_name = "kernel_sync",
    edition = "2021",
    deps = ["//genesis-abi:genesis_abi_rs"],
)

rust_test(
    name = "kernel_sync_test",
    crate = ":kernel_sync",
)

exports_files(["Cargo.toml"])
